<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} --strict --tags ~@wip --tags ~@todo --tags ~@temporarily-disabled -r features/"
%>
default: <%= std_opts %> --require features/ features
pretty: --format pretty --require features/ features
wip: --require features/ --tags @wip --wip features
rerun: <%= rerun_opts %> --require features/ --format rerun --out rerun.txt --strict --tags ~@wip
ci: --require features/ --tags ~@wip --tags ~@broken --tags ~@todo --tags ~@temporarily-disabled --format junit --out reports/acceptance/junit
