defaults: &DEFAULTS
  api_key: 07c77887e7450e5d0d86781a7264c45c
  shared_secret: f6e1a90eb6ab7755
  user: 80288388@N00

development:
  <<: *DEFAULTS

test:
  <<: *DEFAULTS

production:
  <<: *DEFAULTS