defaults: &DEFAULTS
  api_key: 'e0621d7a415e7b84a298989a776551e6'
  shared_secret: '178f91a272579454'
  user: '95789229@N03'
  front_page_tag: 'portfolio'
  background_tag: 'portfolio'

development:
  <<: *DEFAULTS

test:
  <<: *DEFAULTS

production:
  <<: *DEFAULTS
