default:
  theme_advanced_toolbar_location: top
  theme_advanced_toolbar_align: left
  theme_advanced_statusbar_location: bottom
  theme_advanced_buttons3_add:
    - tablecontrols
    - fullscreen
  plugins:
    - table
    - fullscreen

simple:
  theme_advanced_toolbar_location: bottom
  theme_advanced_toolbar_align: right
  theme_advanced_statusbar_location: none
  theme_advanced_buttons1:
    - separator
    - undo
    - redo
    - separator
    - bold
    - italic
    - underline
